# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - id: govulncheck
      name: Run govulncheck
      uses: golang/govulncheck-action@v1

    - name: generate test coverage
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
      
      # Configure action by specifying input parameters individually (option 2).
      # If you are using config file you shouldn't use these parameters.
        profile: cover.out
        threshold-file: 80
        threshold-package: 80
        threshold-total: 95
        git-branch: badges 
